

services:
  web:
    build: .
    container_name: pokemon_fastapi_withoutjwt
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/pokemon_code_1
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: pokemon_postgres_withoutjwt
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Keerth123
      POSTGRES_DB: pokemon_A1_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: