"""adding a column

Revision ID: 5acc87422065
Revises: 9bfc196bcaaf
Create Date: 2025-01-09 21:28:52.948525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acc87422065'
down_revision: Union[str, None] = '9bfc196bcaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('hhhh', sa.String(), nullable=True))
    op.alter_column('pokemon', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('pokemon', 'hhhh')
    # ### end Alembic commands ###
