"""creating tables

Revision ID: 9bfc196bcaaf
Revises: 
Create Date: 2025-01-09 21:20:16.570979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfc196bcaaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('abilities')
    op.drop_table('stats')
    op.drop_table('types')
    op.drop_table('pokemon')
    op.create_table(
        'pokemon',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('weight', sa.Integer(), nullable=True),
        sa.Column('xp', sa.Integer(), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('pokemon_url', sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_pokemon_id'), 'pokemon', ['id'], unique=False)
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=True)

    # Create abilities table

    op.create_table(
        'abilities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pokemon_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('is_hidden', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_abilities_id'), 'abilities', ['id'], unique=False)

    # Create stats table
    op.create_table(
        'stats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pokemon_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('base_stat', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_stats_id'), 'stats', ['id'], unique=False)

    # Create types table
    op.create_table(
        'types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pokemon_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_types_id'), 'types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_types_id'), table_name='types')
    op.drop_table('types')

    # Drop stats table
    op.drop_index(op.f('ix_stats_id'), table_name='stats')
    op.drop_table('stats')

    # Drop abilities table
    op.drop_index(op.f('ix_abilities_id'), table_name='abilities')
    op.drop_table('abilities')

    # Drop pokemon table
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_id'), table_name='pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
